// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rflssziccnuliwsfbwvd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJmbHNzemljY251bGl3c2Zid3ZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1NDE2NjksImV4cCI6MjA1ODExNzY2OX0.AwShG8jYqD1TW3fnWb-KufpkCFGuRVS78KvFs_D_Ngg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);